/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('sections').del()
  await knex('sections').insert([
    {
      id: 1,
      name: 'Ship Cove to Schoolhouse Bay campsite',
      time: '2 hours',
      length: '4.5km',
      notes: '',
      trackId: 1,
    },
    {
      id: 2,
      name: 'Schoolhouse Bay campsite to Endeavour Inlet',
      time: '3 hours',
      length: '10.5km',
      notes: '',
      trackId: 1,
    },
    {
      id: 3,
      name: 'Endeavour Inlet to Camp Bay campsite',
      time: '4 hours',
      length: '11.5km',
      notes: '',
      trackId: 1,
    },
    {
      id: 4,
      name: 'Camp Bay campsite to Torea Saddle(Cowshed Bay campsite)',
      time: '8 hours',
      length: '23 km',
      notes: '',
      trackId: 1,
    },
    {
      id: 5,
      name: 'Torea Saddle(Cowshed Bay campsite) to Mistletoe Bay',
      time: '4 hours',
      length: '8 km',
      notes: '',
      trackId: 1,
    },
    {
      id: 6,
      name: 'Mistletoe Bay to Anakiwa (via Davis Bay campsite)',
      time: '4 hours',
      length: '12.5 km',
      notes: '',
      trackId: 1,
    },
    {
      id: 7,
      name: 'Anakiwa to Havelock',
      time: '4 hours',
      length: '20 km',
      notes: 'Link Pathway',
      trackId: 2,
    },
    {
      id: 8,
      name: 'Havelock to Pelorus Bridge',
      time: '4 hours',
      length: '21 km',
      notes: 'Link Pathway',
      trackId: 2,
    },
    {
      id: 9,
      name: 'Pelorus Bridge to Maungatapu Road end',
      time: '3 - 4 hours',
      length: '14 km',
      notes: 'Link Pathway',
      trackId: 2,
    },
    {
      id: 10,
      name: 'Maungatapu Road end to Captain Creek Hut',
      time: '4 hours',
      length: '8.5 km',
      notes: '',
      trackId: 3,
    },
    {
      id: 11,
      name: 'Captain Creek Hut to Middy Hut',
      time: '2 hours',
      length: '5 km',
      notes: '',
      trackId: 3,
    },
    {
      id: 12,
      name: 'Middy Hut to Rocks Hut',
      time: '3 hours',
      length: '5 km',
      notes: '',
      trackId: 3,
    },
    {
      id: 13,
      name: 'Rocks Hut to Browning Hut',
      time: '4.5 hours',
      length: '11 km',
      notes: '',
      trackId: 3,
    },
    {
      id: 14,
      name: 'Browning Hut to Hacket Junction',
      time: '1 hours',
      length: '3.4 km',
      notes: '',
      trackId: 3,
    },
    {
      id: 15,
      name: 'Hacket Junction to Hacket Hut',
      time: '15 minutes',
      length: '1.3 km',
      notes: '',
      trackId: 4,
    },
  ])
}
